### ISSUE TITLE
Put .latestversion in $HOME

### ISSUE THREAD

**Issue by mj-harvey** [multiscalelab/htmd#10]
Hi @stefdoerr,

Could you change .latestversion to be written to $HOME/.htmd/ please? We can't rely on the conda installation directory being writable.

Matt

**Comment by stefdoerr** [comment]
I did already:
https://github.com/Acellera/htmd/issues/8

**Comment by stefdoerr** [comment]
the changes are in this fork. Give it a try and if it works you can push it to the acellera repo
