### ISSUE TITLE
project  should return 2d array

### ISSUE THREAD

**Issue by tonigi** [multiscalelab/htmd#17]
even when there is only one coordinate, for consistency

**Comment by giadefa** [comment]
why?

**Comment by stefdoerr** [comment]
yes it should

**Comment by stefdoerr** [comment]
Because we always assume that the first dimension are the frames and the second dimension the features

**Comment by tonigi** [comment]
i'm doing the change.

because you want the same code (with two indices) to work independently on the number of CVs.

**Comment by stefdoerr** [comment]
Where are you making the change? My classes always return 2D arrays

**Comment by tonigi** [comment]
in the constructor of metricdata
i got 1d rmsd  (no test case yet)

**Comment by stefdoerr** [comment]
hm okay, I guess it should be fine. I guess you can use np.atleast_2d although you might need to transpose it after

**Comment by tonigi** [comment]
yes that's it

```
        if len(dat.shape) == 1:
            dat2d = np.atleast_2d(dat).T
        else:
            dat2d = dat
```

i'm making a test case

**Comment by tonigi** [comment]
can i assume that all trajectories have the same metric (ie n. of variables?)

**Comment by stefdoerr** [comment]
Yes. I tend to concatenate them into a single array if I want to do some calculation quick.

**Comment by tonigi** [comment]
hmm... changing _processSim instead
