### ISSUE TITLE
Method names like projection()

### ISSUE THREAD

**Issue by tonigi** [multiscalelab/htmd#18]
I find some method names confusing, e.g. `Metric.projection()`. Is it "setProjection" or "addProjection"? Or does it return the current projection?  

In standard OO practice methods names should be verbs. 

I suggest renaming to addProjection().

**Comment by giadefa** [comment]
"set" is misleading and "add" is odd. In what sense is confusing to you?

**Comment by tonigi** [comment]
because it could be anything between set/add/get . It does not describe the action which is going to happen.

**Comment by giadefa** [comment]
In fact, it is anything like set, add and get

**Comment by stefdoerr** [comment]
how so? It only adds, doesn't get and doesn't set

**Comment by tonigi** [comment]
I  would somewhat understand if it was a property, but this is a method...
Il 14 apr 2016 12:43 PM, "Stefan" <notifications@github.com> ha scritto:

**Comment by giadefa** [comment]
if you use it once, it sets
if you use it many times it gets

and is it not also a static method which actually computes it?

**Comment by giadefa** [comment]
i meant
it gets -> it adds

**Comment by stefdoerr** [comment]
There is no static method. And adding does not exclude setting, it just indicates that multiple values can be added. While setting means that only one can be set and if you call it again it will be overwritten.

**Comment by j3mdamas** [comment]
I do agree that, in theory, methods should be actions/verbs

**Comment by giadefa** [comment]
we should have some developper.md file defining the style guide

**Comment by tonigi** [comment]
i'm about to commit   doc/CodingStyle.md

t

**Comment by j3mdamas** [comment]
what about `generateProjection`?

**Comment by stefdoerr** [comment]
no, no. Because we are adding the projections to a list of projections which will be calculated later on.

**Comment by stefdoerr** [comment]
Sure, the typical use case is a single projection, but I think there are many users which want to use multiple projections. Frank's team does it all the time and Toni apparently wanted to do it now as well. So using `setProjection` is out of the question which leaves us with `addProjection` :D

**Comment by tonigi** [comment]
For me `addProjection` is clearer even in the single-projection case. It modifies an empty metric by adding the first one. That's the action. I guess we can leave `projection` as a deprecated method.

**Comment by giadefa** [comment]
but you are not adding in my view

**Comment by j3mdamas** [comment]
I see. Alternatives: `catalogProjection`, `registerProjection` or `enumerateProjection`

**Comment by stefdoerr** [comment]
@giadefa because it's 3v1 at this point ;)  (plus half the internet and software designers)

**Comment by stefdoerr** [comment]
https://msdn.microsoft.com/en-us/library/4df752aw%28v=vs.71%29.aspx
"Use verbs or verb phrases to name methods."

https://en.wikipedia.org/wiki/Naming_convention_%28programming%29#Java
"Methods should be verbs"

http://www.oracle.com/technetwork/java/codeconventions-135099.html
"Methods should be verbs"

http://docs.zope.org/zopetoolkit/codingstyle/python-style.html#attribute-and-method-names
"Method names should always start with a verb that describes the action."

**Comment by j3mdamas** [comment]
But I don't think @giadefa is against having a verb, but the specific `add` verb in this case.

**Comment by stefdoerr** [comment]
well the other ones proposed are even longer and more confusing.

maybe:
`registerProjection`
no:
`catalogProjection`, `enumerateProjection`, `generateProjection`, `setProjection`
because it doesn't catalog, it doesn't enumerate, it does not generate and it does not set.

So between register and add I prefer add for simplicity.

**Comment by tonigi** [comment]
Agreed. For me `addProjection` is the clearest. Alternatives:
 * `registerProjection` (ok but a bit bureaucratic)
 * `appendProjection` (seems a list, but it's not)

After all we have Representation.add() which is logically close.

T

**Comment by giadefa** [comment]
I actually don't like verbs all the times.

For instance, I prefer

mol.boundingBox() to mol.getBoundingBox()

currently is mol.boundingBox()

**Comment by giadefa** [comment]
actually is not a method

**Comment by j3mdamas** [comment]
I vote on `Metric.addProjection`

**Comment by stefdoerr** [comment]
We might also think about adding a `Metric.setSimlist` method in case people don't want to pass the simlist directly at the constructor. It's not totally clear to me why we should pass the simlist in the constructor and the projections through a method.

**Comment by j3mdamas** [comment]
Maybe open a new issue for that one, @stefdoerr?

**Comment by stefdoerr** [comment]
Nah, it's a harmless minor thing. I can just implement it.

**Comment by giadefa** [comment]
agreed
