### ISSUE TITLE
Tica.project() returns wrong dimensions

### ISSUE THREAD

**Issue by tonigi** [multiscalelab/htmd#19]
This seems a consequence of upgrading pyemma `2.0.4-py35_1      --> 2.1-np110py35_0` ...

**Comment by stefdoerr** [comment]
Okay I will take a look at it

**Comment by stefdoerr** [comment]
Can you do a quick test for me?

Change in the TICA class the following lines:

```python
        if ndim is not None:
            self.tic._dim = ndim
            # self.tic.set_params(dim=ndim) # Change to this in new pyEMMA version
```

So comment the one before and uncomment the after

**Comment by tonigi** [comment]
ok it's working (at least the shape)

**Comment by stefdoerr** [comment]
okay I switch to that then since the update pulls the latest pyemma automatically
