### ISSUE TITLE
atom names alignment in pdb

### ISSUE THREAD

**Issue by tonigi** [multiscalelab/htmd#20]
I know you won't like this, but... http://www.biostat.jhsph.edu/~iruczins/teaching/260.655/links/pdbformat.pdf

> Atom names start with element symbols right-justified in columns 13-14 as permitted by the length of the name. For example, the symbol FE for iron appears in columns 13-14, whereas the symbol C for carbon appears in column 14 (see Misaligned Atom Names). If an atom name has four characters, however, it must start in column 13 even if the element symbol is a single character (for example, see Hydrogen Atoms). 

mdanalysis had this problem too (issue 647)  

VMD saves conforming to this  even when the input was misaligned.

**Comment by stefdoerr** [comment]
I don't actually mind changing it. It's a single character I need to add to the print function.
My issue is only about the date of the document (2002) and that there are new standards since then (2008, 2012)

**Comment by j3mdamas** [comment]
Yeah, Stefan is right. Current format is what matters.

On Fri, Apr 15, 2016 at 7:39 PM, Stefan <notifications@github.com> wrote:

> I don't actually mind changing it. It's a single character I need to add
> to the print function.
> My issue is only about the date of the document (2002) and that there are
> new standards since then (2008, 2012)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/multiscalelab/htmd/issues/20#issuecomment-210559518>
>



-- 
João M. Damas
PhD Student
Protein Modelling Group
ITQB-UNL, Oeiras, Portugal
Tel:+351-214469613

**Comment by stefdoerr** [comment]
Yes I said that but I don't know what the current format advises ;) heheh.
We should look around

**Comment by tonigi** [comment]
The most current version  (2008) seems 3.30 at ftp://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_A4.pdf 

> (page 180) Alignment of one-letter atom name such as C starts at column 14, while two-letter atom name such as FE starts at column 13.

the issue on mdanalysis has some in-depth discussion. It may not be trivial to tell CA (calcium) from CA (carbon alpha).

**Comment by stefdoerr** [comment]
Funny thing. AutoDockTools is extremely picky about alignment. It wants the atom names **left aligned** and starting at column 13. Such a mess...

**Comment by tonigi** [comment]
or mdtraj... issue #1094

**Comment by j3mdamas** [comment]
Maybe this issue can be closed?
I was seeing the atom names mismatch in some tests of reading and writing PDBs and now the atom alignment is perfect with the original PDB.

I found mismatch between the residue number alignment though. They were left-aligned in the `PDBParser.writePDB` and I changed them to right-aligned, like in the original PDB file. Solved this tiniest bug in d06dcc3be3a56337dde15e44365a257e49768708

**Comment by stefdoerr** [comment]
Should be fine, but for the future, announce/discuss it a bit more loudly before just dropping a single line that you made a change to such an important piece of code :P

**Comment by j3mdamas** [comment]
You are right. I should have kept it in multiscalehtmd/jmd-devel, link it, and just push after discussion.

Didn't seem to harm much though. It's the same columns, just right aligned instead of left aligned :sweat_smile:

**Comment by stefdoerr** [comment]
Yes, I just get a heart attack when people modify stuff in the PDB writer, haha :D
