### ISSUE TITLE
Don't use empty brackets in function defaults

### ISSUE THREAD

**Issue by stefdoerr** [multiscalelab/htmd#3]
Jesus christ who the hell thought this is a good idea!

```python
def testme(aha=[]):
    aha += 'x'
    print(aha)

for i in range(4):
    testme()

['x']
['x', 'x']
['x', 'x', 'x']
['x', 'x', 'x', 'x']
```

Thanks @mj-harvey!

http://stackoverflow.com/questions/366422/what-is-the-pythonic-way-to-avoid-default-parameters-that-are-empty-lists

**Comment by giadefa** [comment]
i don't understand how this "works". Why this behaviour?

**Comment by mj-harvey** [comment]
I knew you wouldn't believe me..

On 14 March 2016 at 13:20, Stefan <notifications@github.com> wrote:

> Jesus christ who the hell thought this is a good idea!
>
> def testme(aha=[]):
>     aha += 'x'
>     print(aha)
> for i in range(4):
>     testme()
>
> ['x']
> ['x', 'x']
> ['x', 'x', 'x']
> ['x', 'x', 'x', 'x']
>
> Thanks @mj-harvey <https://github.com/mj-harvey>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/multiscalelab/htmd/issues/3>.
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
http://effbot.org/zone/default-values.htm

Function definitions are called once. If a default is a "mutable" it keeps the pointer to that mutable for all function calls.

**Comment by tonigi** [comment]
OMG thanks for the warning

**Comment by mj-harvey** [comment]
I expect it applies to any non-scalar object.

On 14 March 2016 at 16:33, Toni G <notifications@github.com> wrote:

> OMG thanks for the warning
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/multiscalelab/htmd/issues/3#issuecomment-196369983>.
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
mutables actually.
works fine with tuples which are non-mutable
