### ISSUE TITLE
Default capping

### ISSUE THREAD

**Issue by stefdoerr** [multiscalelab/htmd#4]
We cap with neutral caps by default. Is this really the desired behaviour?
It makes sense for:
* proteins missing loops (GPCRs)
* proteins cut out of larger proteins (Villin)

However now that I'm building the OPM I see proteins consisting of multiple natural monomers which are going to get capped now. That could ruin their interactions, right?

I think we should **disable** capping by default instead of enabling it.

**Comment by giadefa** [comment]
as we said before, neutral capping is the best default bet.

**Comment by giadefa** [comment]
I mean compared to charged ones.

If you meant not capping at all, I am not sure how good that is, but
maestro defaults should be fine.

**Comment by stefdoerr** [comment]
Yes, I meant not capping at all. @tonigi what are the Maestro defaults, do you know?

**Comment by tonigi** [comment]
Maestro's default is **charged termini**. If you check the option, you get **ACE/NME capping**.  I think most software defaults to charged termini.

The following two do **not** make sense instead:
* ~~charged capping~~ there is no such a thing IMHO
* ~~neutral termini~~ these only occur at extreme pH, and only at one side.

**Comment by giadefa** [comment]
by charged capping we meant charged termini.

So Maestro seems to use the chemistry view. In the sense that if you do
nothing in a real experiment you will have charged termini and to have
ACE/NME capping you need to perform something to cap them.

In simulation is way more dangerous to use charged termini because there
are lots of cuts where you don't want charges, so I would leave the default
to the less risky ACE/NME.

**Comment by giadefa** [comment]
the alternative is that there is no default and they must be specified.

**Comment by tonigi** [comment]
I agree that ACE-NME is usually safer for MD, but somewhat surprising if it was a default. So I would vote for no default, i.e. mandatory parameter. 

btw Is there a way (even if complicated) to cap one chain but not another?

T

**Comment by stefdoerr** [comment]
Sure, in the charmm.build() function you pass a dictionary with the caps
for each segment (not chain)

**Comment by stefdoerr** [comment]
Keep in mind that to cap in AMBER I need to have the hydrogens (I need to substitute a hydrogen with the cap carbon). Which means that unless you run systemPreparation on the Molecule before building, by default amber.build will crash.

**Comment by tonigi** [comment]
We'll have perhaps to cover the no-H case, in due time.

**Comment by giadefa** [comment]
I would vote for default capping
