### ISSUE TITLE
change to vina location

### ISSUE THREAD

**Issue by mj-harvey** [multiscalelab/htmd#7]
@stefdoerr 

Vina is now present in [CONDA_ROOT]/bin/[platform]-vina[.exe]

where platform == platform.system() ['Linux', 'Darwin', 'Windows' ]
and .exe suffix applies  if the platform is windows

On Linux and Darwin, os.dirname( shutil.which( "python") ) should == [CONDA_ROOT]/bin
but on Windows it gives [CONDA_ROOT],  just to be different (no bin dir on windows)

Could you add that fix, at your convenience, please?

**Comment by stefdoerr** [comment]
I gather you fixed it already?

**Comment by mj-harvey** [comment]
Yep, you can close this

On 16 March 2016 at 15:42, Stefan <notifications@github.com> wrote:

> I gather you fixed it already?
>
> On Tue, Mar 15, 2016 at 5:49 PM, M J Harvey <notifications@github.com>
> wrote:
>
> > @stefdoerr <https://github.com/stefdoerr>
> >
> > Vina is now present in [CONDA_ROOT]/bin/[platform]-vina[.exe]
> >
> > where platform == platform.system() ['Linux', 'Darwin', 'Windows' ]
> > and .exe suffix applies if the platform is windows
> >
> > On Linux and Darwin, os.dirname( shutil.which( "python") ) should ==
> > [CONDA_ROOT]/bin
> > but on Windows it gives [CONDA_ROOT], just to be different (no bin dir on
> > windows)
> >
> > Could you add that fix, at your convenience, please?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/multiscalelab/htmd/issues/7
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/multiscalelab/htmd/issues/7#issuecomment-197360373>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>
